@echo off
setlocal
if not defined LAUNCHSCOPE_DEMO_DEFAULT_WORKSPACE_FILE set "LAUNCHSCOPE_DEMO_DEFAULT_WORKSPACE_FILE=.demo/default-workspace.json"
if not defined LAUNCHSCOPE_MODEL_GATEWAY_PORT set "LAUNCHSCOPE_MODEL_GATEWAY_PORT=8092"
if not defined DELIVERY_SCOPED_MODEL_TOKEN_ENABLED set "DELIVERY_SCOPED_MODEL_TOKEN_ENABLED=true"
if not defined MODEL_USAGE_LEDGER_MODE set "MODEL_USAGE_LEDGER_MODE=GATEWAY_DELIVERY"
if not defined LAUNCHSCOPE_MODEL_REQUEST_TIMEOUT_SECONDS set "LAUNCHSCOPE_MODEL_REQUEST_TIMEOUT_SECONDS=3600"
if not defined LAUNCHSCOPE_WEB_PORT set "LAUNCHSCOPE_WEB_PORT=3000"
if not defined LAUNCHSCOPE_OPS_PORT set "LAUNCHSCOPE_OPS_PORT=3001"
if not defined LAUNCHSCOPE_REPORT_RENDER_WEB_URL set "LAUNCHSCOPE_REPORT_RENDER_WEB_URL=http://127.0.0.1:%LAUNCHSCOPE_WEB_PORT%"
where pwsh >nul 2>&1
if errorlevel 1 (
    echo PowerShell 7 is required but was not found in PATH.
    pause
    exit /b 1
)
pwsh -NoProfile -ExecutionPolicy Bypass -File "%~dp0start.ps1" %*
set "LAUNCHSCOPE_EXIT_CODE=%ERRORLEVEL%"
if not "%LAUNCHSCOPE_EXIT_CODE%"=="0" pause
exit /b %LAUNCHSCOPE_EXIT_CODE%
