"""LaunchScope pure domain kernel.

This package contains only standard-library domain code.  Database, queue,
Agent SDK, cloud and HTTP adapters belong in application/infrastructure
packages and are intentionally absent here.
"""

from .aggregates import (
    ConflictRecord,
    Decision,
    DecisionReport,
    EvaluationRun,
    Evidence,
    EvidenceAudit,
    EvidenceReview,
    Finding,
    MaterialMetadata,
    ProductProfile,
    ProductVersion,
    ProjectDossier,
    Report,
    RetryPolicy,
    RunManifest,
    Stage,
    Task,
    TaskCompletion,
)
from .enums import (
    ALL_DIMENSIONS,
    STAGE_ORDER,
    ApprovalDecision,
    DimensionCode,
    DomainStrEnum,
    EventType,
    EvidenceAuditDecision,
    EvidenceLevel,
    EvidenceSourceType,
    FailureClass,
    FindingGrade,
    NetworkLevel,
    ProductVersionStatus,
    Recommendation,
    RegressionResult,
    RiskTier,
    RunStatus,
    StageCode,
    StageStatus,
    TaskStatus,
)
from .errors import (
    AppendOnlyViolation,
    BudgetError,
    CycleDetectedError,
    DagError,
    DomainError,
    FailClosedError,
    InvalidTransitionError,
    InvariantViolation,
    MissingEvidenceError,
    RetryNotPermittedError,
    TenantScopeViolation,
    ValidationError,
)
from .events import DomainEvent, DomainEventFactory, Event, EventEnvelope, build_event
from .services import (
    DagValidation,
    RuleEvaluation,
    RuleEvaluator,
    RunStateMachine,
    RunStatusMachine,
    RunTransitionContext,
    StageGate,
    TaskDAG,
    TaskDag,
    TaskStateMachine,
    TaskTransitionCheck,
    TransitionCheck,
    TransitionContext,
    evaluate_rules,
    stage_status_is_terminal,
)
from .value_objects import ApprovalBinding, BudgetReservation, CorrelationContext, EvidenceRef, TenantScope, TimeScope

__version__ = "0.1.0"

__all__ = [
    "ALL_DIMENSIONS",
    "ApprovalBinding",
    "ApprovalDecision",
    "AppendOnlyViolation",
    "BudgetReservation",
    "BudgetError",
    "ConflictRecord",
    "CorrelationContext",
    "CycleDetectedError",
    "DagError",
    "DagValidation",
    "Decision",
    "DecisionReport",
    "DimensionCode",
    "DomainError",
    "DomainEvent",
    "DomainEventFactory",
    "DomainStrEnum",
    "EvaluationRun",
    "EventEnvelope",
    "Event",
    "EventType",
    "Evidence",
    "EvidenceAudit",
    "EvidenceAuditDecision",
    "EvidenceLevel",
    "EvidenceRef",
    "EvidenceReview",
    "EvidenceSourceType",
    "FailClosedError",
    "FailureClass",
    "Finding",
    "FindingGrade",
    "InvalidTransitionError",
    "InvariantViolation",
    "MaterialMetadata",
    "ProductProfile",
    "ProductVersion",
    "ProductVersionStatus",
    "ProjectDossier",
    "Recommendation",
    "RegressionResult",
    "RetryNotPermittedError",
    "Report",
    "RetryPolicy",
    "RiskTier",
    "RunManifest",
    "RunStateMachine",
    "RunStatusMachine",
    "RunStatus",
    "RunTransitionContext",
    "Stage",
    "StageCode",
    "StageGate",
    "StageStatus",
    "STAGE_ORDER",
    "Task",
    "TaskCompletion",
    "TaskDAG",
    "TaskDag",
    "TaskStateMachine",
    "TaskStatus",
    "TaskTransitionCheck",
    "TenantScope",
    "TimeScope",
    "TransitionCheck",
    "TransitionContext",
    "NetworkLevel",
    "MissingEvidenceError",
    "TenantScopeViolation",
    "ValidationError",
    "build_event",
    "evaluate_rules",
    "RuleEvaluation",
    "RuleEvaluator",
    "stage_status_is_terminal",
]
